spring.application.name=BeShuffle

# Spotify API
spotify.client.id=${SPOTIFY_CLIENT_ID:13ad5a1231574ce49226682d2303b947}
spotify.client.secret=${SPOTIFY_CLIENT_SECRET:b43ce3f49b1841d89b1ddaa75670bbc5}
spotify.auth.url=https://accounts.spotify.com

# Database
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/beshuffle
spring.datasource.username=postgres
spring.datasource.password=Senhalol.123

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
