spring.application.name=BeShuffle

# Spotify API
client.id=${SPOTIFY_CLIENT_ID}
client.secret=${SPOTIFY_CLIENT_SECRET}
spotify.auth.url=https://accounts.spotify.com

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/beshuffle
spring.datasource.username=postgres
spring.datasource.password=Senhalol.123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
