spring.application.name=BeShuffle

# Spotify API - Carregadas do arquivo .env
spotify.client.id=${SPOTIFY_CLIENT_ID}
spotify.client.secret=${SPOTIFY_CLIENT_SECRET}
spotify.auth.url=https://accounts.spotify.com